events {}

http {
  include       mime.types;
  default_type  application/octet-stream;

  server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
      try_files $uri $uri/ /index.html;
    }

    location /api/webhook/ {
      proxy_pass https://vps22899.cubepath.net/webhook/;
      proxy_set_header Host vps22899.cubepath.net;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_ssl_server_name on;
    }

    location /api/webhook-test/ {
      proxy_pass https://vps22899.cubepath.net/webhook-test/;
      proxy_set_header Host vps22899.cubepath.net;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_ssl_server_name on;
    }
  }
}